import os
from PIL import Image

def verify_order():
    source_img = "stormmultiicoconverter.jpg"
    out_path = "test_order_64first.ico"
    
    if not os.path.exists(source_img):
        print(f"Error: {source_img} not found.")
        return

    try:
        with Image.open(source_img) as img:
            img = img.convert("RGBA")
            # Base must be the largest to ensure quality of others generated by Pillow
            base_256 = img.resize((256, 256), Image.Resampling.LANCZOS)
            
            # Forced order: 64 first, then 256, then others
            forced_sizes = [(64, 64), (256, 256), (128, 128), (48, 48), (32, 32), (16, 16)]
            
            base_256.save(out_path, format='ICO', sizes=forced_sizes)
            print(f"Created {out_path}")
            
    except Exception as e:
        print(f"Creation failed: {e}")

    # Check order
    try:
        with Image.open(out_path) as img:
            print(f"First layer size: {img.size}")
            if img.size == (64, 64):
                print("SUCCESS: 64x64 is the first layer.")
            else:
                print(f"FAILURE: First layer is {img.size}")
                
            if 'sizes' in img.info:
                # Pillow's img.info['sizes'] is a set, so order won't show there.
                # But we can check frames if needed.
                pass
                
    except Exception as e:
        print(f"Verification failed: {e}")

if __name__ == "__main__":
    verify_order()
